# 1. Dirección de la base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/andalucia_datahub
spring.datasource.username=my_user
spring.datasource.password=${DB_PASSWORD}

# 2. Validación de tablas con Hibernate
spring.jpa.hibernate.ddl-auto=validate

# 3. Activamos Flyway
spring.flyway.enabled=true